package UPT_SQ.EduScrumAwards.model;

import jakarta.persistence.*;
import org.hibernate.Session;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Represents a Project entity in the EduScrum Awards system.
 *
 * @author Sania Fatima
 * @version 1.0
 * @since 2025-10-31
 */
@Entity
@Table(name = "projects")
public class Project {

    /**
     * Primary key of the project.
     * Automatically generated by the database using an identity column.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "project_id")
    private int projectId;
    @Column(name = "project_name", length = 50, nullable = false)
    private String projectName;
    @ManyToOne
    @JoinColumn(name = "Team_ID", nullable = false)
    private Team team;
    @ManyToOne
    @JoinColumn(name = "course_id", nullable = false)
    private Course course;

    /**
     * A list of sprints associated with this project.
     */
    @OneToMany(mappedBy = "project", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Sprint> sprints;

    /** Default no-argument constructor required by JPA. */
    public Project() {}

    /**
     * Full constructor to create a project with all fields initialized.
     *
     * @param projectId   Unique project identifier.
     * @param projectName Name of the project.
     * @param team        Team associated with the project.
     * @param course      Course the project belongs to.
     * @param sprints     List of sprints under this project (transient).
     */
    public Project(int projectId, String projectName, Team team, Course course, List<Sprint> sprints) {
        this.projectId = projectId;
        this.projectName = projectName;
        this.team = team;
        this.course = course;
        this.sprints = sprints;
    }

    /** Gets the project's unique identifier. */
    public int getProjectId() {
        return projectId;
    }

    /** Sets the project's unique identifier. */
    public void setProjectId(int projectId) {
        this.projectId = projectId;
    }

    /** Gets the name of the project. */
    public String getProjectName() {
        return projectName;
    }

    /** Sets the name of the project. */
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    /** Gets the team associated with the project. */
    public Team getTeam() {
        return team;
    }

    /** Sets the team for this project. */
    public void setTeam(Team team) {
        this.team = team;
    }

    /** Gets the course the project is part of. */
    public Course getCourse() {
        return course;
    }

    /** Sets the course the project belongs to. */
    public void setCourse(Course course) {
        this.course = course;
    }

    /** Gets the list of sprints under this project (transient). */
    public List<Sprint> getSprints() {
        return sprints;
    }

    /** Sets the list of sprints for this project (transient). */
    public void setSprints(List<Sprint> sprints) {
        this.sprints = sprints;
    }


    public Sprint searchSprint(int sprintId){
        if (sprints == null){
            return null;
        }

        for(Sprint sprint : sprints){
            if(sprint.getSprintId() == sprintId){
                return sprint;
            }
        }
        return null;
    }

    public void retrieveSprints() {

        DatabaseHelper db = new DatabaseHelper();
        db.setup();
        Session session = db.getSessionFactory().openSession();

        session.beginTransaction();

        List<Sprint> sprintList = session.createQuery(
                        "SELECT s FROM Sprint s WHERE s.project.projectId = :pid",
                        Sprint.class
                )
                .setParameter("pid", this.projectId)
                .getResultList();

        this.sprints = new ArrayList<>(sprintList);

        session.getTransaction().commit();
        session.close();
        db.exit();
    }

    public String createSprint(Date startDate, Date endDate, List<Goal> goals){

        if(sprints == null){
            sprints = new ArrayList<>();
        }

        Sprint sprint = new Sprint(startDate, endDate, goals, this);

        for (Goal g : goals) {
            g.setSprint(sprint);
        }

        sprints.add(sprint);

        DatabaseHelper dbHelper = new DatabaseHelper();
        dbHelper.setup();
        Session session = dbHelper.getSessionFactory().openSession();
        session.beginTransaction();
        session.persist(sprint); // now Hibernate will also save goals
        session.getTransaction().commit();
        session.close();
        dbHelper.exit();

        return "Sprint added Successfully!";
    }

    public String updateSprint(int sprintId, Date startDate, Date endDate) {
        if(sprints == null || sprints.isEmpty()){
            return "No sprints found for this project.";
        }

        Sprint sprint = searchSprint(sprintId);
        if(sprint == null){
            return "Sprint with ID " + sprintId + " not found!";
        }

        sprint.setStartDate(startDate);
        sprint.setEndDate(endDate);

        DatabaseHelper dbHelper = new DatabaseHelper();
        dbHelper.setup();
        Session session = dbHelper.getSessionFactory().openSession();
        session.beginTransaction();

        session.merge(sprint);

        session.getTransaction().commit();
        session.close();
        dbHelper.exit();

        return "Sprint updated Successfully!";
    }

    public ArrayList<StudentAward> studentsAwards() {
        DatabaseHelper dbHelper = new DatabaseHelper();
        dbHelper.setup();
        Session session = dbHelper.getSessionFactory().openSession();

        List<StudentAward> list = session.createQuery(
                        "SELECT sa FROM StudentAward sa WHERE sa.project.projectId = :projectId",
                        StudentAward.class
                )
                .setParameter("projectId", this.projectId)
                .getResultList();

        session.close();
        dbHelper.exit();

        return new ArrayList<>(list != null ? list : new ArrayList<>());
    }

    /**
     * Returns a readable string representation of the project.
     * Includes basic project info and the transient sprints field.
     */
    @Override
    public String toString() {
        return "Project{" +
                "projectId=" + projectId +
                ", projectName='" + projectName + '\'' +
                ", team=" + team +
                ", course=" + course +
                ", sprints=" + sprints +
                '}';
    }
}
