package UPT_SQ.EduScrumAwards.model;

import jakarta.persistence.*;
import java.util.List;

/**
 * Represents a Project entity in the EduScrum Awards system.
 *
 * A Project belongs to a specific Team and Course, and may contain multiple Sprints.
 * This entity is mapped to the "projects" table in the database.
 */
@Entity
@Table(name = "projects")
public class Project {

    /**
     * Primary key of the project.
     * Automatically generated by the database using an identity column.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "project_id")
    private int projectId;

    /**
     * The name of the project.
     * Cannot be null and has a maximum length of 50 characters.
     */
    @Column(name = "project_name", length = 50, nullable = false)
    private String projectName;

    /**
     * The team that owns this project.
     * Creates a foreign key column "Team_ID" in the projects table.
     * Many projects can belong to one team.
     */
    @ManyToOne
    @JoinColumn(name = "Team_ID", nullable = false)
    private Team team;

    /**
     * The course this project belongs to.
     * Creates a foreign key column "course_id" in the projects table.
     * Many projects can belong to one course.
     */
    @ManyToOne
    @JoinColumn(name = "course_id", nullable = false)
    private Course course;

    /**
     * A list of sprints associated with this project.
     */
    @Transient
    private List<Sprint> sprints;

    /** Default no-argument constructor required by JPA. */
    public Project() {}

    /**
     * Full constructor to create a project with all fields initialized.
     *
     * @param projectId   Unique project identifier.
     * @param projectName Name of the project.
     * @param team        Team associated with the project.
     * @param course      Course the project belongs to.
     * @param sprints     List of sprints under this project (transient).
     */
    public Project(int projectId, String projectName, Team team, Course course, List<Sprint> sprints) {
        this.projectId = projectId;
        this.projectName = projectName;
        this.team = team;
        this.course = course;
        this.sprints = sprints;
    }

    /** Gets the project's unique identifier. */
    public int getProjectId() {
        return projectId;
    }

    /** Sets the project's unique identifier. */
    public void setProjectId(int projectId) {
        this.projectId = projectId;
    }

    /** Gets the name of the project. */
    public String getProjectName() {
        return projectName;
    }

    /** Sets the name of the project. */
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    /** Gets the team associated with the project. */
    public Team getTeam() {
        return team;
    }

    /** Sets the team for this project. */
    public void setTeam(Team team) {
        this.team = team;
    }

    /** Gets the course the project is part of. */
    public Course getCourse() {
        return course;
    }

    /** Sets the course the project belongs to. */
    public void setCourse(Course course) {
        this.course = course;
    }

    /** Gets the list of sprints under this project (transient). */
    public List<Sprint> getSprints() {
        return sprints;
    }

    /** Sets the list of sprints for this project (transient). */
    public void setSprints(List<Sprint> sprints) {
        this.sprints = sprints;
    }

    /**
     * Returns a readable string representation of the project.
     * Includes basic project info and the transient sprints field.
     */
    @Override
    public String toString() {
        return "Project{" +
                "projectId=" + projectId +
                ", projectName='" + projectName + '\'' +
                ", team=" + team +
                ", course=" + course +
                ", sprints=" + sprints +
                '}';
    }
}
