package UPT_SQ.EduScrumAwards.model;

import jakarta.persistence.*;
import org.hibernate.Session;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Represents a Sprint entity in the EduScrum Awards system.
 *
 * A Sprint belongs to a specific Project and can have multiple Goals.
 * This entity is mapped to the "sprints" table in the database.
 *  * @author Sania Fatima
 *  * @version 1.0
 *  * @since 2025-10-31
 */
@Entity
@Table(name = "sprints")
public class Sprint {

    /**
     * Primary key of the Sprint.
     * Auto-generated by the database using an identity column.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "sprint_id")
    private int sprintId;

    /**
     * The start date of the sprint.
     * Cannot be null. Stored as DATE in the database.
     */
    @Column(name = "start_date", nullable = false)
    @Temporal(TemporalType.DATE)
    private Date startDate;

    /**
     * The end date of the sprint.
     * Cannot be null. Stored as DATE in the database.
     */
    @Column(name = "end_date", nullable = false)
    @Temporal(TemporalType.DATE)
    private Date endDate;

    /**
     * List of Goals associated with this Sprint.
     * Useful for displaying or grouping goals in memory.
     */
    @OneToMany(mappedBy = "sprint", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.EAGER)
    private List<Goal> goals;

    /**
     * The Project this Sprint belongs to.
     * Many Sprints can belong to one Project (ManyToOne relationship).
     * Creates a foreign key column "project_id" in the sprints table.
     */
    @ManyToOne
    @JoinColumn(name = "project_id", nullable = false)
    private Project project;

    /**
     * Default no-argument constructor required by JPA.
     */
    public Sprint() {}

    /**
     * Full constructor to initialize all fields.
     *
     * @param sprintId unique identifier of the Sprint
     * @param startDate start date of the Sprint
     * @param endDate end date of the Sprint
     * @param goals list of Goals associated with this Sprint (transient)
     * @param project the Project this Sprint belongs to
     */
    public Sprint(int sprintId, Date startDate, Date endDate, List<Goal> goals, Project project) {
        this.sprintId = sprintId;
        this.startDate = startDate;
        this.endDate = endDate;
        this.goals = goals;
        this.project = project;
    }

    public Sprint(Date startDate, Date endDate, List<Goal> goals, Project project) {
        this.startDate = startDate;
        this.endDate = endDate;
        this.goals = goals;
        this.project = project;
    }


    // Getters and Setters

    public int getSprintId() {
        return sprintId;
    }

    public void setSprintId(int sprintId) {
        this.sprintId = sprintId;
    }

    public Date getStartDate() {
        return startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public List<Goal> getGoals() {
        return goals;
    }

    public void setGoals(List<Goal> goals) {
        this.goals = goals;
    }

    public Project getProject() {
        return project;
    }

    public void setProject(Project project) {
        this.project = project;
    }

    // ADD GOAL
    public String addGoal(Goal goal) {
        if (goals == null) goals = new ArrayList<>();
        goal.setSprint(this);
        goals.add(goal);

        DatabaseHelper db = new DatabaseHelper();
        db.setup();
        Session session = db.getSessionFactory().openSession();
        session.beginTransaction();
        session.persist(goal);
        session.getTransaction().commit();
        session.close();
        db.exit();

        return "Goal added successfully!";
    }

    //UPDATE GOAL
    public String updateGoal(int goalId, String description, int score, boolean completed) {
        if (goals == null) return "No goals found!";
        Goal goal = goals.stream().filter(g -> g.getGoalId() == goalId).findFirst().orElse(null);
        if (goal == null) return "Goal not found!";

        goal.setDescription(description);
        goal.setScore(score);
        goal.setCompleted(completed);

        DatabaseHelper db = new DatabaseHelper();
        db.setup();
        Session session = db.getSessionFactory().openSession();
        session.beginTransaction();
        session.merge(goal);
        session.getTransaction().commit();
        session.close();
        db.exit();

        return "Goal updated successfully!";
    }

    //RETRIEVE GOAL
    public List<Goal> getAllGoals() {
        return goals;
    }

    // Method to calculate the total score
    public double calcTotalScore(){
        if (goals == null || goals.isEmpty()){
            return 0;
        }
        int totalscore = 0;
        for(Goal goal : goals){
            totalscore += goal.getScore();
        }
        return totalscore;
    }

    public double calcCompletionByScore() {
        double totalScore = calcTotalScore();
        if (totalScore == 0) {
            return 0;
        }
        double completedScore = 0;
        for (Goal goal : goals) {
            if (goal.isCompleted()) {
                completedScore += goal.getScore();
            }
        }
        return (completedScore / totalScore) * 100;
    }
    /**
     * Returns a string representation of the Sprint object.
     * Includes sprintId, start and end dates, and transient goals list.
     */
    @Override
    public String toString() {
        return "Sprint{" +
                "sprintId=" + sprintId +
                ", startDate=" + startDate +
                ", endDate=" + endDate +
                ", goals=" + goals +
                '}';
    }
}
