package UPT_SQ.EduScrumAwards.model;

import jakarta.persistence.*;
import java.util.Date;
import java.util.List;

/**
 * Represents a Sprint entity in the EduScrum Awards system.
 *
 * A Sprint belongs to a specific Project and can have multiple Goals.
 * This entity is mapped to the "sprints" table in the database.
 */
@Entity
@Table(name = "sprints")
public class Sprint {

    /**
     * Primary key of the Sprint.
     * Auto-generated by the database using an identity column.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "sprint_id")
    private int sprintId;

    /**
     * The start date of the sprint.
     * Cannot be null. Stored as DATE in the database.
     */
    @Column(name = "start_date", nullable = false)
    @Temporal(TemporalType.DATE)
    private Date startDate;

    /**
     * The end date of the sprint.
     * Cannot be null. Stored as DATE in the database.
     */
    @Column(name = "end_date", nullable = false)
    @Temporal(TemporalType.DATE)
    private Date endDate;

    /**
     * List of Goals associated with this Sprint.
     * Marked as @Transient because it is not persisted directly by Hibernate.
     * Useful for displaying or grouping goals in memory.
     */
    @Transient
    private List<Goal> goals;

    /**
     * The Project this Sprint belongs to.
     * Many Sprints can belong to one Project (ManyToOne relationship).
     * Creates a foreign key column "project_id" in the sprints table.
     */
    @ManyToOne
    @JoinColumn(name = "project_id", nullable = false)
    private Project project;

    /**
     * Default no-argument constructor required by JPA.
     */
    public Sprint() {}

    /**
     * Full constructor to initialize all fields.
     *
     * @param sprintId unique identifier of the Sprint
     * @param startDate start date of the Sprint
     * @param endDate end date of the Sprint
     * @param goals list of Goals associated with this Sprint (transient)
     * @param project the Project this Sprint belongs to
     */
    public Sprint(int sprintId, Date startDate, Date endDate, List<Goal> goals, Project project) {
        this.sprintId = sprintId;
        this.startDate = startDate;
        this.endDate = endDate;
        this.goals = goals;
        this.project = project;
    }

    // Getters and Setters

    public int getSprintId() {
        return sprintId;
    }

    public void setSprintId(int sprintId) {
        this.sprintId = sprintId;
    }

    public Date getStartDate() {
        return startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public List<Goal> getGoals() {
        return goals;
    }

    public void setGoals(List<Goal> goals) {
        this.goals = goals;
    }

    public Project getProject() {
        return project;
    }

    public void setProject(Project project) {
        this.project = project;
    }

    /**
     * Returns a string representation of the Sprint object.
     * Includes sprintId, start and end dates, and transient goals list.
     */
    @Override
    public String toString() {
        return "Sprint{" +
                "sprintId=" + sprintId +
                ", startDate=" + startDate +
                ", endDate=" + endDate +
                ", goals=" + goals +
                '}';
    }
}
